### ISSUE TITLE
can't run on window or Mac OS system.

### ISSUE THREAD

**Issue by judyssister** [ZhijianZhou01/BioAider#12]
After obtaining the program, users could directly run the program of executable file in the directory of "main", BioAider can run in Windows, Linux(Ubuntu 16.04 or more) and MacOS system.

According to your instruction, the software doesn't work.

**Comment by ZhijianZhou01** [comment]
BioAider has been cited in dozens of publications (in method). In general, it can work normally on Windows systems. If possible, please provide detailed error information. 

Thanks!

**Comment by ZhijianZhou01** [comment]
Resolved: Improper user use
