### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../Configurations/manage_packages.init'

### ISSUE THREAD

**Issue by JuFengWang** [ZhijianZhou01/BioAider#2]
[try@localhost ~]$ /home/try/WJF/soft/dist/main/BioAider
Traceback (most recent call last):
  File "main.py", line 672, in <module>
  File "main.py", line 273, in __init__
  File "main.py", line 481, in package_load
  File "my_funcyion.py", line 99, in load_packages_path
FileNotFoundError: [Errno 2] No such file or directory: '../Configurations/manage_packages.init'
[28348] Failed to execute script main

The executable file reports error when I try to run it. Can you help me to solve it? thanks!

**Comment by ZhijianZhou01** [comment]
Sorry, I didn't see it in time. What is your version of ubuntu, and has the file of “manage_packages.init” been deleted in your directory?

**Comment by ZhijianZhou01** [comment]
What is the version of BioAider used？

**Comment by ZhijianZhou01** [comment]
This bug has been resolved in the latest version (BioAider v1.334) .
