### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Jessie940409** [ZhijianZhou01/BioAider#3]
I downloaded mac version and I met an error when converting seq format from fasta to nexus.
I input a .fasta, the path is "/Users/jessie/Desktop/Bacteria/data/klebsiella/result/0.tree/ST967/core_gene_alignment.fasta"
I want to convert fasta into Nexus, and the data type is nucleotide.
Then an error occurred:

traceback.format_exc():
Traceback (most recent call last):
  File "Seqformat_con.py", line 434, in run
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jessie/Desktop/Bacteria/data/klebsiella/result/0tree/ST967/core_gene_alignment.nex'

When I changed the directory /Users/jessie/Desktop/Bacteria/data/klebsiella/result/0.tree to /Users/jessie/Desktop/Bacteria/data/klebsiella/result/0tree, it works.
So, why a dot appears in the path, then it won't work???

**Comment by ZhijianZhou01** [comment]
Yes, as you could see, BioAider does not allow dots in the names of directories (but files are allowed). As for the reason, the name of output file owns characters added after the original name. This process is replaced by dots as a separator. Therefore, if there are points in the directory, they will be replaced together.

**Comment by ZhijianZhou01** [comment]
This bug has been fixed in version 1.423.
