### ISSUE TITLE
Whether to allow the use of multicore and program background running

### ISSUE THREAD

**Issue by weir12** [ZhijianZhou01/BioAider#4]
Hello: 
Thank you for the development of this powerful and user-friendly software, which is a very valuable software resource for the analysis of viral genome mutations.
 1. Can we allocate multiple cores to shorten the duration of the program (I noticed that Bioaider is a single-threaded mode and can be limited by Python GIL) 
 2. Whether a COMMAND-LINE interface (non-GUI) exists for background running. This way, I can close the current SSH link and let the program keep running until it finishes correctly. 
 
 These two points are very important in the analysis of mutations between a large number of samples (approximately 1 million). Congratulations to my alma mater (HNU) for the development of such excellent program and pipeline.

**Comment by ZhijianZhou01** [comment]
Thank you for your suggestion! These are all good ideas, and they are exactly what we are working on now. However,  due to manpower constraints, many things have been delayed.

**Comment by ZhijianZhou01** [comment]
The COMMAND-LINE interface of  mutations analysis was in https://github.com/ZhijianZhou01/bioaider_mutation. I tried multiple python threads and it didn't work well. This version (V1.423) was algorithm-optimized and much faster.
