### ISSUE TITLE
KeyError: 'X' pop-up

### ISSUE THREAD

**Issue by virologist** [ZhijianZhou01/BioAider#5]
Hi, @ZhijianZhou01 

An error pop-up when I was using Mutation analysis.
```
traceback.format_exc():
Traceback (most recent call last):
  File "mutation_analysis.py", line 1436, in run
  File "my_funcyion.py", line 1018, in aa_kind_dis
KeyError: 'X'
```
I think this error may cause by incomplete codon translation.
![image](https://user-images.githubusercontent.com/54756814/140456388-7a6e3856-dbc1-4264-8b21-cdc6ae45342a.png)
Any idea?

Best wishes,
Yang

**Comment by ZhijianZhou01** [comment]
OK, "aa_kind_dis" is a comparison table  of AA properties, and the special character "X" was not in this table. You could try to delete the character X and the gap after it, it might work properly. We would add the character "X" in subsequent versions of BioAider.
Best wishes,
Zhou

**Comment by virologist** [comment]
Hi, @ZhijianZhou01 

Thanks for your reply. 
I am waiting for your new version release.

Best wishes,
Yang
