### ISSUE TITLE
小bug反馈

### ISSUE THREAD

**Issue by pengouy** [ZhijianZhou01/BioAider#6]
你好：
你这个软件做得好棒，今天刚听说，只能说我知道得太晚。发现一点小bug，你可以看看是什么情况。
**主要问题：**我用BioAider把fasta序列转换成nexus格式后，输入BEAUti软件，再传入时间信息，发现凡是名字中含有-的序列所对应的时间均不能被识别。相同的时间信息，我把Geneious转换后的nexus文件传进去就能被正确识别，不知道是什么原因造成的。
祝：软件做得原来越完善！

**Comment by ZhijianZhou01** [comment]
您好：
   我用手上的序列进行了测试，没有发现这种问题。目前我这边的Geneious版本不支持将fasta转为nex，尚不清楚Geneious转换后做了哪些更改。如果您方便的话，可以把您出错的序列发我，以便我确认是否是软件bug导致的。
